version: '0.0.1'

services:

  e-faktur-database:
    image: postgres:16.1
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 3001:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
      - PGTZ=${PG_TZ}
      - TZ=${TZ}
    env_file:
      - .env

  e-faktur-cache:
    image: redis:7.2.4
    volumes:
      - ./cache_data:/var/lib/redis/data
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASS"
    ports:
      - 3002:6379
    env_file:
      - .env

volumes:
  e-faktur-database:
    driver: local
  e-faktur-cache:
    driver: local